--From the table DEPARTMENT and PERSON perform the following queries:  
--Part – A: 
--1. Combine information from Person and Department table using cross join or Cartesian product. 

	SELECT * FROM PERSON
	CROSS JOIN DEPARTMENT

--2. Find all persons with their department name 

	SELECT PERSONNAME,DEPARTMENTNAME FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID

--3. Find all persons with their department name & code. 

	SELECT PERSONNAME,DEPARTMENTNAME,DEPARTMENT.DEPARTMENTID FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID

--4. Find all persons with their department code and location. 

	SELECT  CITY,DEPARTMENT.DEPARTMENTCODE FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID

--5. Find the detail of the person who belongs to Mechanical department. 

	SELECT * FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	WHERE DEPARTMENTNAME='MECHANICAL'

--6. Final person’s name, department code and salary who lives in Ahmedabad city.  

	SELECT PERSONNAME,DEPARTMENTCODE,SALARY FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	WHERE CITY='AHMEDABAD'

--7. Find the person's name whose department is in C-Block.

	SELECT PERSONNAME FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	WHERE LOCATION='C-Block'

--8. Retrieve person name, salary & department name who belongs to Jamnagar city. 

	SELECT PERSONNAME,SALARY,DEPARTMENTNAME FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	WHERE CITY='JAMNAGAR'

--9. Retrieve person’s detail who joined the Civil department after 1-Aug-2001. 

	SELECT * FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	WHERE DEPARTMENTNAME='CIVIL' AND JOININGDATE > '2001-08-01'

--10. Display all the person's name with the department whose joining date difference with the current date 

	SELECT PERSONNAME,DEPARTMENTNAME FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	WHERE DATEDIFF(YEAR,PERSON.JOININGDATE,GETDATE()) > 25

--is more than 25 years. 
--11. Find department wise person counts. 

	SELECT DEPARTMENTNAME,COUNT(*) FROM PERSON
	INNER JOIN DEPARTMENT
	ON PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	GROUP BY DEPARTMENT.DEPARTMENTNAME

--12. Give department wise maximum & minimum salary with department name. 

	SELECT DEPARTMENTNAME,MIN(SALARY),MAX(SALARY) FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	GROUP BY DEPARTMENTNAME

--13. Find city wise total, average, maximum and minimum salary. 

	SELECT CITY ,SUM(SALARY), MAX(SALARY), MIN(SALARY),AVG(SALARY) FROM PERSON
	GROUP BY CITY


--14. Find the average salary of a person who belongs to Ahmedabad city. 

	SELECT AVG(SALARY) FROM PERSON
	WHERE CITY ='AHMEDABAD'

--15. Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In 
--single column) 
 
	SELECT PERSONNAME+CITY+DEPARTMENTNAME FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID

--Part – B: 
--16. Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In 
--single column) 

	SELECT PERSONNAME+CAST(SALARY AS varchar)+DEPARTMENTNAME FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID

--17. Find city & department wise total, average & maximum salaries. 

	SELECT CITY ,DEPARTMENTNAME,SUM(SALARY),MAX(SALARY),MIN(SALARY) FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	GROUP BY CITY,DEPARTMENTNAME

--18. Find all persons who do not belong to any department. 

	SELECT PERSONNAME FROM PERSON
	INNER JOIN DEPARTMENT
	ON PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	WHERE DEPARTMENTNAME IS NULL 

--19. Find all departments whose total salary is exceeding 100000. 
 
	SELECT DEPARTMENTNAME FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	WHERE SALARY = 100000

--Part – C: 
--20. List all departments who have no person. 

	SELECT DEPARTMENTNAME FROM PERSON
	INNER JOIN DEPARTMENT
	ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	WHERE PERSONNAME IS NULL

--21. List out department names in which more than two persons are working. 

	SELECT DEPARTMENTNAME,COUNT(*) FROM PERSON
	INNER JOIN DEPARTMENT
	ON PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	GROUP BY DEPARTMENTNAME
	HAVING COUNT(PERSONNAME)>2

--22. Give a 10% increment in the computer department employee’s salary. (Use Update)