--From the table STUDENT_INFO and RESULT perform the following queries:  
--Part – A: 
--1. Combine information from Student and Result table using cross join (Cartesian product). 

	SELECT * FROM STUDENT_INFO
	CROSS JOIN RESULT

--2. Perform inner join on Student and Result tables. 

	SELECT * FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO = RESULT.RNO

--3. Perform the left outer join on Student and Result tables. 

	SELECT * FROM STUDENT_INFO
	LEFT OUTER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO

--4. Perform the right outer join on Student and Result tables. 

	SELECT * FROM STUDENT_INFO
	RIGHT OUTER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO

--5. Perform the full outer join on Student and Result tables. 

	SELECT * FROM STUDENT_INFO
	FULL OUTER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO

--6. Display Rno, Name, Branch and SPI of all students. 

	SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH, RESULT.SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON RESULT.RNO=STUDENT_INFO.RNO

--7. Display Rno, Name, Branch and SPI of CE branch students only. 

	SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH, RESULT.SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.BRANCH='CE' AND STUDENT_INFO.RNO=RESULT.RNO

--8. Display Rno, Name, Branch and SPI of students other than EC branch. 

	SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH, RESULT.SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.BRANCH!='EC' AND STUDENT_INFO.RNO=RESULT.RNO 

--9. Display Rno, Name and SPI of students whose SPI is greater than 8. 

	SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH, RESULT.SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON RESULT.SPI>8 AND STUDENT_INFO.RNO=RESULT.RNO

--10. Display Rno, Name and Branch of students whose SPI is less than 8.

	SELECT STUDENT_INFO.RNO,STUDENT_INFO.NAME,STUDENT_INFO.BRANCH, RESULT.SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON RESULT.SPI<8 AND STUDENT_INFO.RNO=RESULT.RNO

--11. Display average result of each branch. 

	SELECT STUDENT_INFO.BRANCH, AVG(RESULT.SPI) AS AVG_RESULT FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH

--12. Display average result of CE and ME branch. 

	SELECT STUDENT_INFO.BRANCH, AVG(RESULT.SPI) AS AVG_RESULT FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH
	HAVING BRANCH IN('CE','ME')

--13. Display maximum and minimum SPI of each branch. 

	
	SELECT STUDENT_INFO.BRANCH, MIN(RESULT.SPI) AS MIN_SPI,MAX(RESULT.SPI) AS MAX_SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH

--14. Display branch-wise student count in descending order. 

	SELECT STUDENT_INFO.BRANCH, COUNT(*) AS TOTAL_STUDENT FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH 
	ORDER BY COUNT(*) DESC

--15. Display branch-wise total SPI of students. 

	SELECT STUDENT_INFO.BRANCH, SUM(RESULT.SPI) AS TOTAL_SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH

 
--Part – B: 
--16. Display branch-wise number of students having SPI greater than 8.

	SELECT STUDENT_INFO.BRANCH, COUNT(*) AS TOTAL_STUDENT FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO AND RESULT.SPI>8
	GROUP BY BRANCH

--17. Display branch-wise number of students having SPI less than 8. 

	SELECT STUDENT_INFO.BRANCH, COUNT(*) AS TOTAL_STUDENT FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO AND RESULT.SPI<8
	GROUP BY BRANCH

--18. Display branch-wise average SPI greater than 7. 

	SELECT STUDENT_INFO.BRANCH, AVG(RESULT.SPI) AS TOTAL_STUDENT FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH
	HAVING AVG(RESULT.SPI)>7

--19. Display branches having more than 1 students. 

	SELECT STUDENT_INFO.BRANCH, COUNT(*) AS TOTAL_STUDENT FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH 
	HAVING COUNT(*)>1

--20. Display branches where maximum SPI is greater than 9. 

	SELECT STUDENT_INFO.BRANCH, MAX(RESULT.SPI) AS MAX_SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH
	HAVING MAX(RESULT.SPI)>9

 
--Part – C: 
--21. Display average result of each branch and sort them in ascending order by SPI. 

	SELECT STUDENT_INFO.BRANCH, AVG(RESULT.SPI) AS TOTAL_STUDENT FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH
	ORDER BY AVG(RESULT.SPI) ASC

--22. Display highest SPI from each branch and sort them in descending order. 

	SELECT STUDENT_INFO.BRANCH, MAX(RESULT.SPI) AS MAX_SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH

--23. Display average result of each branch and sort them in ascending order by SPI. 

	SELECT STUDENT_INFO.BRANCH, AVG(RESULT.SPI) AS MAX_SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH
	ORDER BY AVG(RESULT.SPI) ASC

--24. Display highest SPI from each branch and sort them in descending order. 

	SELECT STUDENT_INFO.BRANCH, MAX(RESULT.SPI) AS MAX_SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH
	ORDER BY MAX(RESULT.SPI) DESC

--25. Display branches where difference between max and min SPI is greater than 1.

	SELECT STUDENT_INFO.BRANCH, MIN(RESULT.SPI) AS MIN_SPI,MAX(RESULT.SPI) AS MAX_SPI FROM STUDENT_INFO
	INNER JOIN RESULT
	ON STUDENT_INFO.RNO=RESULT.RNO
	GROUP BY BRANCH
