--From the table DEPOSIT perform the following queries:  
--Part – A:  
--1. Copy all records from DEPOSIT where AMOUNT > 3000 into HIGH_AMOUNT.  

	SELECT * INTO HIGH_AMOUNT
	FROM DEPOSIT
	WHERE AMOUNT > 3000
	SELECT * FROM HIGH_AMOUNT

--2. Copy only CNAME and AMOUNT from DEPOSIT where BNAME = 'MAVDI' into MAVDI_CUSTOMERS.  

	SELECT CNAME , AMOUNT INTO MAVDI_CUSTOMERS
	FROM DEPOSIT
	WHERE BNAME='MAVDI'

--3. Copy records of DEPOSIT where ADATE > '2025-01-01' into RECENT_DEPOSITS.

	SELECT * INTO RECENT_DEPOSITS
	FROM DEPOSIT
	WHERE ADATE > '2025-01-01'
	SELECT * FROM RECENT_DEPOSITS

--4. Copy distinct BNAME from DEPOSIT into BRANCH_LIST.  

	SELECT DISTINCT BNAME INTO BRANCH_LIST
	FROM DEPOSIT
	SELECT * FROM BRANCH_LIST

--5. Copy top 5 records from DEPOSIT into TOP_DEPOSITS. 

	SELECT TOP 5 * INTO TOP_DEPOSITS
	FROM DEPOSIT

--6. Copy records where AMOUNT between 2000 and 6000 into MID_RANGE. 

	SELECT * INTO MID_RANGE
	FROM DEPOSIT
	WHERE AMOUNT BETWEEN 2000 AND 6000

--7. Copy distinct branch names from DEPOSIT into UNIQUE_BRANCH. 

	SELECT DISTINCT BNAME INTO UNIQUE_BRANCH
	FROM DEPOSIT

--8. Copy records with NULL branch into NO_BRANCH_ASSIGNED.  

	SELECT * INTO NOM_BRANCH_ASSIGNED
	FROM DEPOSIT
	WHERE BNAME = 'NULL'
	

--9. Copy all records and rename AMOUNT as BALANCE into DEPOSIT_COPY. 

	SELECT  * INTO DEPOSIT_COPY
	FROM DEPOSIT
	EXEC sp_rename 'DEPOSIT_COPY.AMOUNT' , 'BALANCE'
	SELECT * FROM DEPOSIT_COPY

--10. Copy records where BNAME in ('MAVDI','BEDI') into SELECTED_BRANCH. 

	SELECT * INTO SELECTED_BRANCH
	FROM DEPOSIT 
	WHERE BNAME IN ('MAVDI','DESI')
 
--From the table Student perform the following queries:  
--Part – B:  
--11. Create a new table STUDENT_BACKUP from STUDENT without copying any data. 

	SELECT * INTO STUDENT_BACKUP
	FROM STUDENT
	WHERE 1=0

--12. Copy SNAME and CITY where BRANCH = 'COMPUTER' into CS_STUDENTS.

	SELECT SNAME , CITY INTO CS_STUDENTS
	FROM STUDENT
	WHERE BRANCH='COMPUTER'
	SELECT * FROM STUDENT

--13. Copy top 3 students based on SPI into TOPPER_LIST. 

	SELECT TOP 3 SPI INTO TOPPER_LIST
	FROM STUDENT

--14. Copy distinct CITY from STUDENT into CITY_LIST. 

	SELECT DISTINCT CITY INTO CITY_LIST
	FROM STUDENT

--15. Copy records where STDID between 103 and 108 into MID_STUDENTS. 

	SELECT * INTO MID_STUDENTS
	FROM STUDENT
	WHERE STDID BETWEEN 103 AND 108

--From the table Student perform the following queries:  
--Part – C:  
--16. Copy records with NULL branch into NULL_BRANCH_STUDENTS. 

	SELECT * INTO NULL_BRANCH_STUDENTS
	FROM STUDENT
	WHERE BRANCH IS NULL

--17. Copy all STUDENT records and rename SPI as PERFORMANCE into STUDENT_COPY. 

	SELECT * INTO STUDENT_COPY
	FROM STUDENT
	EXEC sp_rename 'STUDENT_COPY.SPI' , 'PERFORMANCE'

--18. Copy records where CITY in ('RAJKOT','SURAT') into CITY_WISE.  

	SELECT * INTO CITY_WISE
	FROM STUDENT
	WHERE CITY IN ('RAJKOT','SURAT')

--19. Copy students where BRANCH <> 'CIVIL' into NON_CIVIL_STUDENTS. 

	SELECT * INTO NON_CIVIL_STUDENTS
	FROM STUDENT
	WHERE BRANCH <> 'CIVIL'
	SELECT * FROM NON_CIVIL_STUDENTS

--20. Copy selected columns (SNAME, CITY) from STUDENT table into a new table.

	SELECT SNAME,CITY INTO NEW_STUDENT
	FROM STUDENT
	SELECT * FROM STUDENT
